---
- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages for OS
  ansible.builtin.package:
    name={{ item.name }}
    version={{ item.version | default(omit) }}
  with_items: "{{ os_packages }}"
  become: true
  when: os_packages is defined

- name: Install  pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: forcereinstall
    executable: pip3
    extra_args: "--user --upgrade {{ container_lab__pip_install_extra_args }}"
    umask: "0022"
  changed_when: false
  with_items: "{{ python_packages }}"
  when: python_packages is defined

- name: Run Container LAB
  community.docker.docker_container:
    name: "{{ container_lab__name }}"
    image: "{{ container_lab__image }}"
    restart_policy: unless-stopped
    networks: "{{ container_lab__networks }}"
    env: "{{ container_lab__default_env | combine(container_lab__env) }}"
    volumes: "{{ container_lab__directory_volumes }}"
    log_driver: "{{ container_lab__log_driver }}"
    log_options: "{{ container_lab__log_options }}"
